const ROLES = {
  TENANT: "TENANT",
  MANAGER: "MANAGER",
  MAINTENANCE: "MAINTENANCE"
};

const APPLICATION_STATUS = {
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED"
};

const MAINTENANCE_STATUS = {
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED"
};

module.exports = { ROLES, APPLICATION_STATUS, MAINTENANCE_STATUS };