const ROLES = {
  TENANT: "TENANT",
  MANAGER: "MANAGER",
  MAINTENANCE: "MAINTENANCE"
};

const AUTH_MODES = {
  JWT: "jwt",
  KEYCLOAK: "keycloak"
};

const AUTH_SOURCES = {
  JWT: "jwt",
  KEYCLOAK: "keycloak"
};

const APPLICATION_STATUS = {
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED"
};

const MAINTENANCE_STATUS = {
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED"
};

const PAYMENT_METHODS = {
  CARD: "CARD",
  BANK_TRANSFER: "BANK_TRANSFER",
  CASH: "CASH"
};

module.exports = {
  ROLES,
  AUTH_MODES,
  AUTH_SOURCES,
  APPLICATION_STATUS,
  MAINTENANCE_STATUS,
  PAYMENT_METHODS
};
